name: 🐞 Bug report
description: Help us improve jsrepo.
labels: ["bug"]
title: "bug: "
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for helping us fix jsrepo!
              Before continuing make sure you have checked other issues to see if your issue has already been reported / addressed.
    - type: textarea
      id: desc
      attributes:
          label: Describe the issue
          description: What is happening right now? What is supposed to happen?
          placeholder: When I ... jsrepo ... but it should ...
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              ## Reproduction

              Most of the time it will be difficult to reproduce your issue if we don't have access to the source registry. 
              Please provide a public registry from any supported provider that can be used to reproduce your issue.

              **For build issues**: 
              Provide a link to the source repository where the issue can be reproduced as well as any reproduction steps.

              **For install issues**:
              Using the public registry please reproduce your issue in our [project template](https://stackblitz.com/github/ieedan/jsrepo/tree/main/examples/project) then provide a link to the instance as well as any reproduction steps.
    - type: input
      id: registry-link
      attributes:
          label: Registry Link
          description: Link the registry to use to reproduce.
          placeholder: https://github.com/ieedan/std
      validations:
          required: false
    - type: input
      id: repro-link
      attributes:
          label: Reproduction Link
          description: Link to the reproduction.
          placeholder: https://github.com/ieedan/jsrepo-repro
      validations:
          required: true
    - type: textarea
      id: repro-steps
      attributes:
          label: Steps to reproduce
          description: What steps should be taken to reproduce your issue. 
          placeholder: |
            Run:

            ```
            jsrepo add utils/math
            ```
      validations:
          required: true
    - type: checkboxes
      id: terms
      attributes:
          label: Validations
          description: Please make sure you have checked all of the following.
          options:
              - label: I have checked other issues to see if my issue was already reported or addressed
                required: true
